environment_class: HorizontalEnvironment

unreal:
  #scene_file:
  #  /home/bhepp/Documents/UnrealProjects/CustomScenes/CustomScenes.uproject
  scene_path:
    /home/bhepp/Documents/UnrealProjects/
  scene_name: CustomScenes
  map_path:
    /Game/maps/houses
  map_name: buildings
  #map_name: medieval_building
  #width: 640
  #height: 480
  width: 320
  height: 240
  #width: 160
  #height: 120
  #fps: 50

octomap:
  voxel_size: 0.2
  max_range: 20.0
  voxel_free_threshold: 0.25
  voxel_occupied_threshold: 0.75
  observation_count_saturation: 3.0
  naive_scan_insertion: false
  use_only_surface_voxels_for_score: true
  surface_voxels_filename: ""
  binary_surface_voxels_filename:
    /home/bhepp/Documents/UnrealProjects/CustomScenes/Export/buildings/surface_voxels.bin

camera:
  width: 320
  height: 1
  fov: 90.0

world_bounding_box: [[-18, -20, 3.1], [+23, +18, 3.1]]
score_bounding_box: [[-14, -17.5, 3.1], [+19.5, +15, 3.1]]

collision:
  obs_level: 1
  obs_sizes: [3, 3, 1]

collect_data:
  obs_levels: [0, 1, 2, 3, 4]
  obs_sizes: [16, 16, 1]
  reset_interval: 500
  reset_score_threshold: 0.5
  downsample_to_grid: False

